// <auto-generated />
using System;
using AetherEyeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AetherEyeAPI.Migrations
{
    [DbContext(typeof(AetherEyeDbContext))]
    [Migration("20250124120000_AgregarCamposVentaCliente")]
    partial class AgregarCamposVentaCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            // Esta es una migración manual, el modelo completo se maneja en AetherEyeDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
